import { Button, HStack, Menu, MenuButton, MenuItem, MenuList } from "@chakra-ui/react";
import { FaChevronDown } from "react-icons/fa6";

const filterOptionsFounder = [
  {
    label: "Background",
    property: "Background",
    values: ["All", "Boxes", "Lines", "Margin", "Rough", "Wrinkled", "Yellow"],
  },
  {
    label: "Body",
    property: "Body",
    values: ["All", "Alpha", "Cool", "Friendly", "Pink", "Vibrant"],
  },
  {
    label: "Clothing",
    property: "Clothing",
    values: [
      "All",
      "Akatsuki",
      "Disco",
      "Gladiator",
      "Hawaiian",
      "Hoodie",
      "Karate",
      "Move",
      "Ocean",
      "Shinobi",
      "Spartan",
      "Toga",
      "Waldo",
      "Wizard",
    ],
  },
  {
    label: "Face",
    property: "Face",
    values: ["All", "Angry", "Annoyed", "Happy", "Neutral", "Stoic"],
  },
  {
    label: "Headgear",
    property: "Headgear",
    values: ["All", "Bandana", "Beanie", "Hair", "Headset", "Laurel", "Ninja", "Pirate", "Spartan", "Wizard"],
  },
  {
    label: "Unique",
    property: "Unique",
    values: [
      "All",
      "Boombox",
      "Boxing",
      "Guitar",
      "Lei",
      "Magician",
      "Palette",
      "Skateboard",
      "Spartan",
      "Spray",
      "Zeus",
    ],
  },
];

const filterOptionsCommunity = [
  {
    label: "Background",
    property: "Background",
    values: [
      "All",
      "Aged",
      "Antique",
      "Canvas",
      "Crumpled",
      "Grid Blueprint",
      "Kraft",
      "Notebook",
      "Parchment Vintage",
      "Ruled Classic",
      "Smooth",
    ],
  },
  {
    label: "Body",
    property: "Body",
    values: [
      "All",
      "Ash",
      "Charcoal",
      "Clay",
      "Cream",
      "Desert",
      "Earth",
      "Emerald",
      "Jungle Green",
      "Lavender",
      "Lime",
      "Maroon",
      "Mint",
      "Mustard",
      "Navy",
      "Neon",
      "Ocean",
      "Orchid",
      "Parchment",
      "Plum",
      "Rose",
      "Sand",
      "Sand Beige",
      "Seafoam",
      "Shadow Grey",
      "Sienna",
      "Sky",
      "Sunset",
      "Teal",
      "Violet",
    ],
  },
  {
    label: "Clothing",
    property: "Clothing",
    values: [
      "All",
      "Adventurer",
      "Aloha",
      "Astronaut Gravity",
      "Astronaut Infinite",
      "Astronaut Nebula",
      "Astronaut Star",
      "Beach",
      "Business Bacon",
      "Business Broccoli",
      "Business Burgundy",
      "Business Charcoal",
      "Business Cinder",
      "Business Comics",
      "Business Ebony",
      "Business Forest",
      "Business Green",
      "Business Holidays",
      "Business Jade",
      "Business Linen",
      "Business Mahogany",
      "Business Midnight",
      "Business Moss",
      "Business Navy",
      "Business Olive",
      "Business Onyx",
      "Business Plum",
      "Business Purple",
      "Business Steel",
      "Business Tree",
      "Business Wine",
      "Captain Banana Black",
      "Captain Banana Golden",
      "Cherrywood",
      "Cobalt",
      "Coco",
      "Cool",
      "Creamy Beige",
      "Crimson",
      "Eco",
      "Elite",
      "Essence",
      "Forest Green",
      "Golden Top",
      "Golden Wheat",
      "Greenhouse",
      "Hazard",
      "Hobbit Clover",
      "Hobbit Dandelion",
      "Hobbit Fern",
      "Hobbit Hazelnut",
      "Hobbit Honey",
      "Hobbit Meadow",
      "Hobbit Moss",
      "Hobbit Mushroom",
      "Hobbit Oak",
      "Hobbit Thistle",
      "Hobbit Willow",
      "Homeless Princess",
      "Horn",
      "Hunter",
      "Island",
      "Ivory",
      "Jungle Foliage",
      "Jungle Glade",
      "Jungle Overgrowth",
      "Jungle Thicket",
      "Jungle Vines",
      "Kingdom Coronet",
      "Kingdom Crown",
      "Kingdom Diadem",
      "Kingdom Scepter",
      "Kingdom Throne",
      "Leon's T-shirt Earth",
      "Leon's T-shirt Fire",
      "Leon's T-shirt Green",
      "Leon's T-shirt Jungle",
      "Leon's T-shirt Ocean",
      "Leon's T-shirt Shadow",
      "Leon's T-shirt Storm",
      "Leon's T-shirt Sun",
      "Leon's T-shirt Teal",
      "Leisure",
      "Luau",
      "Mai Tai",
      "Mahogany",
      "Oasis",
      "Olive",
      "Onyx",
      "Outlander Discovery",
      "Outlander Explorer",
      "Outlander Horizon",
      "Outlander Nomad",
      "Outlander Odyssey",
      "Outlander Pathfinder",
      "Outlander Seeker",
      "Outlander Summit",
      "Outlander Trailblazer",
      "Outlander Voyage",
      "Outlander Wayfarer",
      "Paradise",
      "Peril",
      "Pineapple",
      "Pilot Prowler",
      "Pilot Rascal",
      "Pilot Rogue",
      "Prehistoric Beast",
      "Prehistoric Bone",
      "Prehistoric Primeval",
      "Prehistoric Savage",
      "Prehistoric Untamed",
      "Prehistoric Wild",
      "Red",
      "Rugby Green",
      "Rugby Ocean",
      "Rugby Purple",
      "Rugby Red",
      "Rugby Teal",
      "Rustic Red",
      "Samba",
      "Santa",
      "Scout Discovery",
      "Scout Horizon",
      "Scout Outpost",
      "Scout Outrider",
      "Scout Pioneer",
      "Scout Seeker",
      "Scout Tracker",
      "Scout Wander",
      "Scout Wilderness",
      "Serenity",
      "Sheriff Badge",
      "Sheriff Duty",
      "Sheriff Honor",
      "Sheriff Justice",
      "Shimmer",
      "Sunshine",
      "Surf",
      "Tiki",
      "Topic",
      "Tranquility",
      "Tropical",
      "Uniform Battalion",
      "Uniform Corps",
      "Uniform Division",
      "Uniform Duty",
      "Uniform Regiment",
      "Uniform Squadron",
      "Village Herbalist",
      "Village Merchant",
      "Village Woodworker",
      "Voyager",
      "Warden",
    ],
  },
  {
    label: "Face",
    property: "Face",
    values: [
      "All",
      "Amused",
      "Angry",
      "Curious",
      "Cigar",
      "Devious",
      "Disappointed",
      "Fancy",
      "Farming",
      "Furious",
      "Grumpy",
      "Jealous",
      "Neutral",
      "Not Amused",
      "Rebel",
      "Sad",
      "Suspicious",
      "Stoned",
      "Unbothered",
      "Wise",
      "Worried",
    ],
  },
  {
    label: "Hair",
    property: "Hair",
    values: [
      "All",
      "Adventurer Cure",
      "Adventurer Go",
      "Adventurer Nox",
      "Adventurer Xeno",
      "Adventurer Ypsilon",
      "Adventurer Zeta",
      "Astro Celestial",
      "Astro Cosmos",
      "Astro Pilot",
      "Astro Spacefarer",
      "Astro Stargazer",
      "Bonehead",
      "Captain Banana Black",
      "Captain Banana Golden",
      "Cyber Shades",
      "Digital Specs",
      "Elite",
      "Explorer Adventurer",
      "Explorer Pathfinder",
      "Explorer Seeker",
      "Explorer Voyager",
      "Floppy (1)",
      "Floppy (2)",
      "Future Sight",
      "Headphones",
      "Horn",
      "Lucky",
      "Pixel Peep",
      "Pilot Prowler",
      "Pilot Rascal",
      "Pilot Rogue",
      "Pirate Blackbeard",
      "Pirate Buccaneer",
      "Pirate Cutthroat",
      "Pirate Privateer",
      "Pirate Sea Dog",
      "Racoon",
      "Rugby Dragon",
      "Rugby Iron",
      "Rugby Raven",
      "Rugby War",
      "Rugby Wing",
      "Santa",
      "Sheriff Cap",
      "Straw Hat Boater",
      "Straw Hat Brim",
      "Straw Hat Sunseeker",
      "Tech Vision",
      "Viking",
      "Wizard Conjurer",
      "Wizard Enchanter",
      "Wizard Illusionist",
      "Wizard Sorcerer",
      "Wizard Spellweaver",
    ],
  },
  {
    label: "Unique",
    property: "Unique",
    values: [
      "All",
      "Axe",
      "Banana",
      "Bike Beige",
      "Bike Black",
      "Bike Brown",
      "Bone Shard",
      "Bow",
      "Club",
      "Fish Rod",
      "Hook",
      "Horn",
      "Lantern",
      "Mic",
      "Pipe",
      "Pitchfork",
      "Scimitar",
      "Shotgun",
      "Spear",
      "Staff",
      "Torch",
      "Whale",
      "Wukong",
    ],
  },
];

interface NFTFilterProps {
  collectionName: string;
  filter: Record<string, string>;
  onFilterChange: (property: string, value: string) => void;
}

function NFTFilter({ collectionName, filter, onFilterChange }: NFTFilterProps) {
  const filterOptions = collectionName === "founder" ? filterOptionsFounder : filterOptionsCommunity;

  return (
    <HStack paddingBottom={4} wrap="wrap">
      {filterOptions.map((option) => (
        <Menu key={option.property}>
          <MenuButton
            as={Button}
            rightIcon={<FaChevronDown />}
            colorScheme={filter[option.property] ? "green" : "gray"}
          >
            {option.label} {filter[option.property] ? `: ${filter[option.property]}` : ""}
          </MenuButton>
          <MenuList maxHeight="500px" overflowY="auto">
            {option.values.map((value) => (
              <MenuItem key={value} onClick={() => onFilterChange(option.property, value)}>
                {value}
              </MenuItem>
            ))}
          </MenuList>
        </Menu>
      ))}
    </HStack>
  );
}

export default NFTFilter;
