[package]
name = "Gorilla Moverz"
version = "0.0.1"

[addresses]
GorillaMoverz = "8f8045299964708acb332287ef304ee5be081b790a7a21e05647090e8ac28cdc"
initial_creator_addr = "8f8045299964708acb332287ef304ee5be081b790a7a21e05647090e8ac28cdc"
minter = "0x8f8045299964708acb332287ef304ee5be081b790a7a21e05647090e8ac28cdc"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", rev = "mainnet", subdir = "aptos-move/framework/aptos-token-objects" }
TokenMinter = { git = "https://github.com/aptos-labs/token-minter.git", rev = "main", subdir = "token-minter" }

[dev-dependencies]
