create table "public"."banana_farm_allowlist" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "discord_user_id" text,
    "discord_user_name" text,
    "wallet_address" text
);


alter table "public"."banana_farm_allowlist" enable row level security;

CREATE UNIQUE INDEX banana_farm_allowlist_discord_user_id_key ON public.banana_farm_allowlist USING btree (discord_user_id);

CREATE UNIQUE INDEX banana_farm_allowlist_pkey ON public.banana_farm_allowlist USING btree (id);

CREATE UNIQUE INDEX banana_farm_allowlist_wallet_address_key ON public.banana_farm_allowlist USING btree (wallet_address);

alter table "public"."banana_farm_allowlist" add constraint "banana_farm_allowlist_pkey" PRIMARY KEY using index "banana_farm_allowlist_pkey";

alter table "public"."banana_farm_allowlist" add constraint "banana_farm_allowlist_discord_user_id_key" UNIQUE using index "banana_farm_allowlist_discord_user_id_key";

alter table "public"."banana_farm_allowlist" add constraint "banana_farm_allowlist_wallet_address_key" UNIQUE using index "banana_farm_allowlist_wallet_address_key";

grant delete on table "public"."banana_farm_allowlist" to "anon";

grant insert on table "public"."banana_farm_allowlist" to "anon";

grant references on table "public"."banana_farm_allowlist" to "anon";

grant select on table "public"."banana_farm_allowlist" to "anon";

grant trigger on table "public"."banana_farm_allowlist" to "anon";

grant truncate on table "public"."banana_farm_allowlist" to "anon";

grant update on table "public"."banana_farm_allowlist" to "anon";

grant delete on table "public"."banana_farm_allowlist" to "authenticated";

grant insert on table "public"."banana_farm_allowlist" to "authenticated";

grant references on table "public"."banana_farm_allowlist" to "authenticated";

grant select on table "public"."banana_farm_allowlist" to "authenticated";

grant trigger on table "public"."banana_farm_allowlist" to "authenticated";

grant truncate on table "public"."banana_farm_allowlist" to "authenticated";

grant update on table "public"."banana_farm_allowlist" to "authenticated";

grant delete on table "public"."banana_farm_allowlist" to "service_role";

grant insert on table "public"."banana_farm_allowlist" to "service_role";

grant references on table "public"."banana_farm_allowlist" to "service_role";

grant select on table "public"."banana_farm_allowlist" to "service_role";

grant trigger on table "public"."banana_farm_allowlist" to "service_role";

grant truncate on table "public"."banana_farm_allowlist" to "service_role";

grant update on table "public"."banana_farm_allowlist" to "service_role";