-- Step 1: Create the banana_farm_collections table
create table public.banana_farm_collections (
  id bigint generated by default as identity,
  name text not null,
  slug text not null,
  collection_address text not null,
  created_at timestamp with time zone not null default now(),
  constraint banana_farm_collections_pkey primary key (id)
) tablespace pg_default;

-- Step 2: Add the collection_id column to the banana_farmer table
alter table public.banana_farmer
add column collection_id bigint;

-- Step 3: Insert an initial collection into the banana_farm_collections table
insert into public.banana_farm_collections (name, slug, collection_address) values ('Banana Farmer | Gorilla Moverz', 'farmer', '0xba47e8a4111d53d81773e920b55c4152976a47ea4b002777cd81e8eb6ed9e4e2');

-- Step 4: Update existing rows in the banana_farmer table to reference the initial collection
update public.banana_farmer
set collection_id = (select id from public.banana_farm_collections where slug = 'farmer');

-- Step 5: Make the collection_id column not nullable and add the foreign key constraint
alter table public.banana_farmer
alter column collection_id set not null,
add constraint banana_farmer_collection_id_fkey foreign key (collection_id) references public.banana_farm_collections (id);

alter table public.banana_farmer rename to banana_farm_nfts;

alter table public.banana_farm_nfts
  add column nft_number bigint;

-- Update the nft_number column to have the same value as the id field
update public.banana_farm_nfts
set nft_number = id;

-- Alter the column to be not nullable
alter table public.banana_farm_nfts
  alter column nft_number set not null;
  