create table
  public.partner (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    name text not null,
    socials text null,
    contact_discord text null,
    description text null,
    benefits_gorillaz text null,
    benefits_partner text null,
    comments text null,
    constraint partner_pkey primary key (id)
  ) tablespace pg_default;

create trigger "discord-webhook"
after insert on partner for each row
execute function supabase_functions.http_request (
  'http://host.docker.internal:54321/functions/v1/discord-webhook',
  'POST',
  '{"Content-type":"application/json","Authorization":"Bearer ***"}',
  '{}',
  '5000'
);